right_format = """$nodejs $cmd_duration $time"""

[cmd_duration]
#format = '[$duration]($style)'

[git_commit]
disabled = false
only_detached = false

[nodejs]
#format = '[$symbol($version)]($style)'

[time]
disabled = false
#format = 'at [$time]($style)'

