---
git_personal_conf: "{{ ansible_facts['user_dir'] }}/.gitconfig.personal"
git_professional_conf: "{{ ansible_facts['user_dir'] }}/.gitconfig.professional"

git_editor: "vim"
git_fullname: "Fullname"
git_personal_email: "email@home.com"
git_professional_email: "email@work.com"
