- name: Common base configuration
  hosts: all

  vars_files:
    - default.config.yml
    - config.yml

  pre_tasks:
    - name: Verify Ansible meets setup version requirements
      ansible.builtin.assert:
        that: "ansible_version.full is version('2.15', '>=')"
        fail_msg: "You must update Ansible to at least 2.15 to use this setup."
      tags: ['always']

  tasks:
    - name: Import SSH key tasks
      ansible.builtin.import_tasks: tasks/ssh_key.yml
      tags: ['ssh', 'minimal']

- name: Workstation base configuration
  hosts: workstations

  vars_files:
    - default.config.yml
    - config.yml

  pre_tasks:
    - name: Verify Ansible meets operating system requirements (Fedora)
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == 'RedHat'
          - ansible_facts['distribution'] == 'Fedora'
        fail_msg: "This workstation playbook is explicitly designed for Fedora."
      tags: ['always']

  tasks:
    - name: Import NVM tasks
      ansible.builtin.import_tasks: tasks/nvm.yml
      tags: ['nvm']

    - name: Import Google Chrome tasks
      ansible.builtin.import_tasks: tasks/google_chrome.yml
      tags: ['chrome']

  roles:
    - role: git
      tags: ['git', 'minimal']

    - role: vim
      tags: ['vim', 'minimal']

    - role: zsh
      tags: ['zsh']

    - role: vscode
      tags: ['vscode']

    - role: docker
      tags: ['docker']
