- name: Global Linux configuration
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Verify Ansible meets setup version requirements
      ansible.builtin.assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: "You must update Ansible to at least 2.8 to use this setup."
      tags: ['always']

    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/ssh_key.yml
      tags: ['ssh']

  roles:
    - role: git
      tags: ['git']

    - role: vim
      tags: ['vim']

    - role: zsh
      tags: ['zsh']

    - role: chrome
      tags: ['chrome']
