---
- name: Import Google Chrome GPG key
  become: true
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install Google Chrome
  become: true
  ansible.builtin.dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
    disable_gpg_check: false
