---
- name: Add Google Chrome repository
  become: true
  ansible.builtin.yum_repository:
    name: google-chrome
    description: Google Chrome Repository
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    skip_if_unavailable: true

- name: Install Google Chrome
  become: true
  ansible.builtin.dnf:
    name: google-chrome-stable
    state: present
    update_cache: true
