- name: Create home ssh directory
  ansible.builtin.file:
    path: "~/.ssh/"
    state: directory
    mode: 0755

- name: Generate ssh private and public keys
  community.crypto.openssh_keypair:
    path: "~/.ssh//id_rsa"
