- name: Create home .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh"
    state: directory
    mode: '0700'

- name: Generate SSH private and public keys (ED25519)
  community.crypto.openssh_keypair:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh/id_ed25519"
    type: ed25519
    mode: '0600'
