---
- name: Check if atuin is installed
  ansible.builtin.command: which atuin
  register: zsh_atuin_check
  failed_when: false
  changed_when: false

- name: Install Atuin
  when: zsh_atuin_check.rc != 0
  ansible.builtin.shell:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh | sh
    creates: "{{ ansible_facts['user_dir'] }}/.atuin/bin/atuin"
  environment:
    ATUIN_NO_MODIFY_PATH: "1"
  changed_when: true
