---
- name: Import base zsh installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import CLI tools tasks
  ansible.builtin.import_tasks: tools.yml

- name: Import Starship setup tasks
  ansible.builtin.import_tasks: starship.yml

- name: Import Atuin setup tasks
  ansible.builtin.import_tasks: atuin.yml

- name: Import fnm setup tasks
  ansible.builtin.import_tasks: fnm.yml
