---
- name: Import base zsh installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Oh My Zsh setup tasks
  ansible.builtin.import_tasks: oh-my-zsh.yml
  when: zsh_enable_omz | bool

- name: Import Powerlevel10k setup tasks
  ansible.builtin.import_tasks: powerlevel10k.yml
  when: zsh_enable_omz | bool
