---
- name: Clone Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ omz_dir }}"
    version: master

- name: Install zsh plugins
  ansible.builtin.git:
    repo: https://github.com/zsh-users/{{ item }}.git
    dest: "{{ omz_custom_dir }}/plugins/{{ item }}"
    depth: 1
    version: master
  with_items:
    - zsh-syntax-highlighting
    - zsh-autosuggestions

- name: Check if zshrc file exists
  ansible.builtin.stat:
    path: "{{ zshrc_file }}"
  register: zshrc

- name: Create zshrc file
  ansible.builtin.copy:
    src: "{{ omz_dir }}/templates/zshrc.zsh-template"
    dest: "{{ zshrc_file }}"
    mode: 0644
  when: not zshrc.stat.exists

- name: Configure zsh plugins
  ansible.builtin.lineinfile:
    path: "{{ zshrc_file }}"
    regexp: ^plugins=
    line: plugins=(zsh-syntax-highlighting zsh-autosuggestions sudo web-search)
