---
- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present
    update_cache: true

- name: Import personal Git setup tasks
  ansible.builtin.import_tasks: personal.yml

- name: Import professional Git setup tasks
  ansible.builtin.import_tasks: professional.yml

- name: Import global Git setup tasks
  ansible.builtin.import_tasks: global.yml
