---
# - name: Install git
#   become: true
#   ansible.builtin.package:
#     name: git
#     state: present

- import_tasks: personal.yml

- import_tasks: professional.yml

- import_tasks: global.yml
