---
- name: Create professional project directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/Projects/professional"
    state: directory
    mode: '0755'

- name: Configure professional git user parameters
  community.general.git_config:
    name: "user.{{ item.name }}"
    value: "{{ item.value }}"
    scope: file
    file: "{{ git_professional_conf }}"
  with_items:
    - {name: "name", value: "{{ git_fullname }}"}
    - {name: "email", value: "{{ git_professional_email }}"}
