---
- name: Install Third Party Repositories
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - fedora-workstation-repositories
    - dnf-plugin-config-manager
