---

- name: Add Google Chrome repository
  become: true
  ansible.builtin.copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo
    mode: 0644
    force: false

- name: Import Google Chrome signing key
  become: true
  ansible.builtin.rpm_key:
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
