---
- name: Add Google Chrome repository and key
  become: true
  ansible.builtin.deb822_repository:
    name: google-chrome
    types: deb
    uris: https://dl.google.com/linux/chrome/deb/
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://dl.google.com/linux/linux_signing_key.pub
    install_python_debian: true
    state: present
