- name: Add docker-ce repository
  become: true
  ansible.builtin.get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    mode: 0644

- name: Install latest version of Docker Engine (and docker-compose)
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-compose
