name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 0 1 * *" # Automatic check every month at 00:15
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint ansible-core

      - name: Lint code
        run: ansible-lint -vv
        env:
          ANSIBLE_GALAXY_CLI_ARGUMENTS: "--clear-response-cache"

  integration:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: "Ubuntu 26.04 (Latest)"
            image: "geerlingguy/docker-ubuntu2604-ansible:latest"
          - name: "Fedora 44 (Latest)"
            image: "geerlingguy/docker-fedora44-ansible:latest"

    container:
      image: ${{ matrix.distro.image }}
      options: --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:rw

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the test environment
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          ansible-galaxy install -r requirements.yml

      - name: Test the playbook
        run: |
          ansible-playbook playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook playbook.yml --diff | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
